#ifndef GUARD_CONSTANTS_SHINING_TRIAL_H
#define GUARD_CONSTANTS_SHINING_TRIAL_H

#define SHINING_TRIAL_ELIGIBLE             0
#define SHINING_TRIAL_NO_MON               1
#define SHINING_TRIAL_EGG                  2
#define SHINING_TRIAL_ALREADY_SHINY        3
#define SHINING_TRIAL_FRIENDSHIP_TOO_LOW   4
#define SHINING_TRIAL_NO_SHINY_FORM        5

#define SHINING_TRIAL_FINISH_SUCCESS       0
#define SHINING_TRIAL_FINISH_IDENTITY_LOST 1
#define SHINING_TRIAL_FINISH_INELIGIBLE    2
#define SHINING_TRIAL_FINISH_NO_PID        3

#endif // GUARD_CONSTANTS_SHINING_TRIAL_H
